# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e0aa3b7767b39140311c9028d697ebb4bbd26e9b64ca30610d9b1369bd584919fd913dd761a7ceb681569ff66cb5679aa07facaa34e7a539f1c2c111b50a5e4

test:
  secret_key_base: cd39253e4fa33d9ba9d72e8eb9c4bac44ba83fb2e95cb0517f095f87aef82e418c8feb695405e88df047472bc748827f3a674cf6d0005b1aca3f634ee61b085d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
